import os
from dotenv import load_dotenv

load_dotenv()

AWS_REGION = os.getenv("AWS_REGION")
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION")
S3_BUCKET = os.getenv("S3_BUCKET")
RAW_FOLDER = os.getenv("RAW_PREFIX")
PROCESSED_FOLDER = os.getenv("PROCESSED_PREFIX")
GLUE_DATABASE = os.getenv("GLUE_DB")
ATHENA_RESULTS_FOLDER = os.getenv("ATHENA_RESULTS_PREFIX")
CURATED_FOLDER = os.getenv("CURATED_PREFIX")
ROLE_ARN = os.getenv("ROLE_ARN")
PROCESSING_INSTANCE_TYPE = os.getenv("PROCESSING_INSTANCE_TYPE")
BEDROCK_MODEL_ID = os.getenv("BEDROCK_MODEL_ID")
